### ISSUE TITLE
Cannot find 3rdpart/utf8.h

### ISSUE THREAD

**Issue by shailendrapundhir** [zenden2k/curl-cpp-wrapper#1]
While using the files in some project , i constantly get this error, as there is not such file.Please let me know if we can find this file and /or upload the same in your project.

Thanks btw. Its an awesome library.

**Comment by zenden2k** [comment]
I have added missing files and made a few changes in existing files
https://github.com/zenden2k/curl-cpp-wrapper/commit/ab06571f69e19bbf3cbcf96621b4d8d8bd472ca4
